### ISSUE TITLE
Option for Persistent Notification when updates are available

### ISSUE THREAD

**Issue by schneekluth** [hacs/integration#1148]
## Category
- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## The idea
Create an option for a persistent notification with a direct link to the HACS interface when updates are available. That way you can be informed about updates and directly navigate to the installation page. Currently I am using these 2 automations that work well:

```yaml
- alias: HACS Update Persistent Notification Create
  trigger:
    - above: '0'
      entity_id: sensor.hacs
      platform: numeric_state
  condition:
    - condition: template
      value_template: '{{ not is_state("sensor.hacs", "unknown") }}'
  action:
    - data:
        message: "[Update available!](https://MY_HASS_URL/hacs/installed)"
        title: HACS
        notification_id: "1234"
      service: persistent_notification.create

- alias: HACS Update Persistent Notification Dismiss
  trigger:
    - platform: state
      entity_id: sensor.hacs
      to: '0'
  action:
    - data:
        notification_id: "1234"
      service: persistent_notification.dismiss
```

## Implementation
You could probably read the [`base_url`](https://www.home-assistant.io/integrations/http/#base_url) setting for the generated url of the hass instance to create the hyperlink in the notification. Or maybe as an input field to declare the base url manually.

## Alternatives
Stick to those 2 automations.
