### ISSUE TITLE
Lovelace frontend plugins are not found in YAML mode, despite correct URLs. Error: Custom element doesn't exist

### ISSUE THREAD

**Issue by recklessnl** [hacs/integration#1299]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.0.3
| Home Assistant version     | 0.110.4
| Installation method for HA | Docker
| Web browser                | Firefox
| Web browser version        | 77.0.1

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Recently I moved the resources section from my ``ui-lovelace.yaml` to my `configuration.yaml`. I have this code in there:

```
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
```

This should correctly load the modules (all installed and managed by HACS) but it doesn't show any of them: I always get the **Custom element doesn't exist** error for all of them. I never had this issue before recent updates.

There are more people with this issue: https://community.home-assistant.io/t/custom-element-doesnt-exist/196741/9

### Steps to reproduce

Here's code from `ui-lovelace.yaml` that produces the error:

```
-       id: 91a25b0a229327ba4211eba7d2e964  # Automatically created id
        type: entities
        show_header_toggle: false
        entities:
          - type: custom:slider-entity-row
            entity: light.livingroom
            name: Living Room ALL
```
### Screenshots

![image](https://user-images.githubusercontent.com/41142401/83848425-7c2f3400-a6d3-11ea-8741-99fd9007303e.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>
