### ISSUE TITLE
Expose a `hacs.update` service which allows for updating of repos

### ISSUE THREAD

**Issue by kquinsland** [hacs/integration#1303]
## Category

- [X] Backend/Integration
- [ ] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

I am happy that there is a HACS sensor which allows me to [check for notifications](https://hacs.xyz/docs/basic/automation). I am asking for the next logical step: a service that i can call from within home assistant to update a given repository.

The idea is simple: create an automation that simply updates a repo if there is an update available.

## Implementation

I'm not versed on the HA code base so I can't give actual code, but I would imagine that a service would be the best way to implement this. I used the [`python_script` service](https://github.com/home-assistant/core/blob/f1d3c0d19b4065a1f6ec80ecdc080380f728196c/homeassistant/components/python_script/__init__.py) as an example implementation

## Alternatives

> Are there any alternative solutions or features you've considered?

Possibly a python script that can be called via the `python_script` service which emulates the web browser / user clicking the `update` button for a given registry.

I am not aware of any way to update a given repo other than to manually do it via click / user action.

## Additional context

Ideally i'd like to do some automation like this:

```yaml

  - alias: applies HACS updates
    trigger:
      platform: state
      entity_id: sensor.hacs
    condition:
     # Apply updates, but only after 1 AM
      condition: and
          conditions:
            - condition: time
              after: '01:00:00'
      
             # It looks like the `hacs` sensor will be a positive integer when there's some repository
             #     that needs updates.
            - condition: template
              value_template: "{{ states(trigger.entity_id) != 'unknown'}}"
            - condition: template
              value_template: "{{ (states(trigger.entity_id) | float) != 0}}"

    action:
      service: hacs.update_repos
      data_template:
       # Pass in a list of repos to update
        repos: {{ state_attr(trigger.entity_id, 'repositories') }}

```

Note: hand-crafted YAML in browser so it might be a few indents away from valid... but hopefully you get the point of what i'm going for.

I would _fully_ support wrapping this automation in some documentation that makes it _very_ clear to the user that blindly updating things w/o first checking for breaking changes or other incompatibilities is a **bad idea**.  My _full_ usecase is a bit more elaborate and involves an automation that puts a  `todo: check $HACS_REPO_NAME changelog` on my todo list and only after completing the task does a flag get set which acts as a gate/whitelist of sorts for the actual HACS update call. This way, the repo is only updated after ive checked for breaking changes. 

But i felt that it would be much simpler to demonstrate a usecase for the service via a simple time. trigger :)
