### ISSUE TITLE
Integration shown as not loaded but it is

### ISSUE THREAD

**Issue by DavidFW1960** [hacs/integration#786]
## Version of HACS
17.1

## Describe the bug
iPhone tracker showing with a red icon. It is loaded in config and it's working. Just hacs shows red icon. It is up to date too.

## Debug log

```text
There is no error as such. 
Add your logs here.

```

**Comment by ludeeus** [comment]
Which repository is this?

**Comment by DavidFW1960** [comment]
Iphone device tracker https://github.com/mudape/iphonedetect

**Comment by aptonline** [comment]
I’m also seeing the same behaviour for a number of my integrations and plugins.

**Comment by ludeeus** [comment]
I don't see it for any of mine

**Comment by Spankythemusical** [comment]
Because I originally came here looking for answers to this exact question, I would recommend checking the URL entry for each of the integrations.  Some of them have change, albeit ever so slightly.  

i.e.:

`- type: module
    url: /community_plugin/mini-media-player/mini-media-player.js`

is now:

`-  type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js `

I've already changed a few of mine and they changed from "Not Loaded" to "Installed."  Hopefully this helps.

**Comment by ludeeus** [comment]
And that change happened in 0.13.0

**Comment by SentryMax** [comment]
My system issues after the HACS update
1-iPhone tracker showing with a red icon. It is loaded in config and it's working. Just hacs shows red icon. It is up to date too.
From the logs after changing the url as suggested here. 
2-http://192.168.1.2:8123/hacs_frontend/main.js?v=0.17.1:1:1 SyntaxError: redeclaration of const z
3-http://192.168.1.2:8123/community_plugin/mini-media-player/mini-media-player-bundle.js:1:71700 NotSupportedError: Cannot define multiple custom elements with the same tag name
4-http://192.168.1.2:8123/community_plugin/simple-weather-card/simple-weather-card-bundle.js:1:2564 NotSupportedError: Cannot define multiple custom elements with the same tag name
5-http://192.168.1.2:8123/community_plugin/unused-card/unused-card.js:1:1 SyntaxError: redeclaration of let k

**Comment by Spankythemusical** [comment]
If it did, it didn't show its ugly head until now, as these issues were not present through all the other updates.  I'm in the position now where I'm basically having to reinstall and re-add most of the items that had been working fine until this update.

**Comment by ludeeus** [comment]
Remember to clear your browser cache Everytime you change Lovelace resources

**Comment by SentryMax** [comment]
Issues persist after a browser cache clearing.

**Comment by Shadowpheonix** [comment]
I also have this issue.

This is with HACS 16.3...
![With HACS 16 3](https://user-images.githubusercontent.com/32688453/69061807-20bb8400-09d7-11ea-9fe1-e94e032a65d3.png)

And here's HACS 17.1...
![With HACS 17 1](https://user-images.githubusercontent.com/32688453/69061805-20bb8400-09d7-11ea-93c2-cff56c47c913.png)


(FYI, the 16.3 screen shot was taken _after_ upgrading HACS, then rolling back because of this issue.)

On a side note, am I the only one that actually prefers the user interface from 16.3?   17.1 just looks so cluttered and the cards are huge.

**Comment by PrathikGopal** [comment]
Same with me, got many in red -showing not loaded.
![image](https://user-images.githubusercontent.com/38837781/69064306-f6ec7680-0a43-11ea-99d1-94ef96779cfa.png)

**Comment by walthowd** [comment]
Also same for me:
![Screenshot 2019-11-18 09 13 14](https://user-images.githubusercontent.com/864569/69064375-b3622000-09e3-11ea-97a6-1caa8b05c257.png)

Here is my lovelace config:
```
resources:
  - type: module
    url: /local/community/weather-card/weather-card.js?v=3
  - type: module
    url: /local/community/mini-graph-card/mini-graph-card.js?v=4
  - type: js
    url: /local/community/zha-network-card/zha-network-card.js?v=3
  - type: js
    url: /local/community/dual-thermostat/dual-thermostat.js?v=3
  - type: js
    url: /local/community/calendar-card/calendar-card.js?v=1
  - type: js
    url: /local/community/flex-table-card/flex-table-card.js?v=1
  - type: js
    url: /local/community/lovelace-auto-entities/auto-entities.js?v=1
```

Not sure on the distinction between **community** and **community_plugin** -- Never changed or configured HACS but it always puts files in **community** and the install examples always show **community_plugin**. 

I tried moving over a few plugins manually to **community_plugin** but that didn't help.
