### ISSUE TITLE
Can't add to lovelace

### ISSUE THREAD

**Issue by allanpersson** [hacs/integration#845]
## Version of HACS
0.18

## Describe the bug
First thank you for making add to lovelace directly from HACS 👏 it worked with all my plug-ins and integrations except one. 
![Screenshot_20191208-161805_Home Assistant](https://user-images.githubusercontent.com/46043392/70391592-1f2e1c00-19d7-11ea-8cbd-296e8c2e0248.jpg)
I deleted everything in my resources before using HACS to add to lovelace for all of them. I'm not sure if it's a bug in the plug in, HACS or my installation 

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
What is in the resources?

**Comment by allanpersson** [comment]
```
resources:
  - type: module
    url: /community_plugin/atomic_calendar/atomic_calendar.js
  - type: module
    url: /community_plugin/banner-card/banner-card.js
  - type: module
    url: /community_plugin/lovelace-auto-entities/auto-entities.js
  - type: module
    url: /community_plugin/compact-custom-header/compact-custom-header.js
  - type: js
    url: /community_plugin/rejseplanen-card/rejseplanen-card.js
  - type: module
    url: /community_plugin/lovelace-card-tools/card-tools.js
  - type: module
    url: /community_plugin/button-card/button-card.js
  - type: module
    url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
  - type: js
    url: /community_plugin/logbook-card/logbook-card.js
  - type: js
    url: /community_plugin/secondaryinfo-entity-row/secondaryinfo-entity-row.js
  - type: module
    url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
  - type: js
    url: /community_plugin/love-lock-card/love-lock-card.js
  - type: js
    url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
  - type: module
    url: /community_plugin/swipe-card/swipe-card.js
  - type: module
    url: >-
      /community_plugin/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
  - type: js
    url: /community_plugin/miflora-card/miflora-card.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
```

All of them was manually added, then i removed them and used the new function to add them directly from HACS. The only one failing is the light entity row (Reinstall of the plugin is tried)
